version: "3"

networks:
  homelab:
    name: homelab
    external: true

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}

    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOAD_DIR}/torrent:/downloads

    # ports:
    #   - 8080:8080   # WebUI
    #   - 8118:8118   # Privoxy - if using VPN

    networks:
      - homelab
