version: '3'

networks:
  homelab:
     name: homelab
     external: true

services:
  vaultwarden:
    image: vaultwarden/server:1.29.2-alpine
    container_name: vaultwarden
    restart: unless-stopped

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      # access
      DOMAIN: "https://vaultwarden.${HOMELAB_DOMAIN}"
      ADMIN_TOKEN: "${VAULTWARDEN_ADMIN_TOKEN}"
      # features
      SIGNUPS_ALLOWED: "true"
      SIGNUPS_VERIFY: "true"
      WEBSOCKET_ENABLED: "true"
      INVITATIONS_ALLOWED: "true"
      INVITATION_ORG_NAME: "${VAULTWARDEN_ORG}"
      # email contact
      SMTP_FROM_NAME: "Vaultwarden"
      SMTP_FROM: "${SENDGRID_EMAIL}"
      # sendgrid auth
      SMTP_USERNAME: "${SENDGRID__SMTP_USERNAME}"
      SMTP_PASSWORD: "${SENDGRID__SMTP_PASSWORD}"
      SMTP_HOST: "${SENDGRID_SMTP_HOST}"
      SMTP_PORT: "${SENDGRID_SMTP_PORT}"
      SMTP_AUTH_MECHANISM: "${SENDGRID__SMTP_AUTH_MECHANISM}"
      SMTP_SECURITY: "${SENDGRID_SMTP_SECURITY}"

    volumes:
      - ${CONFIG_DIR}/vaultwarden:/data

    logging:
      driver: "json-file"

    networks:
      - homelab

  vaultwarden-backup:
    image: ttionya/vaultwarden-backup:1.19.2
    container_name: vaultwarden-backup
    restart: unless-stopped

    depends_on:
      - vaultwarden

    environment:
      TIMEZONE: "${TZ}"
      # schedule
      CRON: "0 */4 * * *"
      BACKUP_KEEP_DAYS: 30
      BACKUP_FILE_DATE_SUFFIX: "_%H%M"
      # rclone
      RCLONE_REMOTE_NAME: "${RCLONE_REMOTE}"
      RCLONE_REMOTE_DIR: "${RCLONE_BACKUP_DIR}/vaultwarden/"
      RCLONE_GLOBAL_FLAG: ""
      # backup compression
      ZIP_ENABLE: "true"
      ZIP_PASSWORD: "${VAULTWARDEN_ZIP_PASSWORD}"
      ZIP_TYPE: "7z"

    volumes:
      - ${CONFIG_DIR}/vaultwarden:/bitwarden/data
      - ${CONFIG_DIR}/vaultwarden-backup:/config/

    networks:
      - homelab
