version: '3'

networks:
  homelab:
    name: homelab
    external: true

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped

    volumes:
      - ${CONFIG_DIR}/nginx-proxy-manager/data:/data
      - ${CONFIG_DIR}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

    ports:
      - 81:81     # WebUI
      - 80:80     # HTTP
      - 443:443   # HTTPS

    networks:
      - homelab
